export const dummyProjects = [
  {
    propertyName: "Skyline Towers",
    propertyType: "luxury",
    city: "Mumbai",
    state: "Maharashtra",
    address: "Bandra West, Mumbai",
    minPrice: 25000000,
    maxPrice: 50000000,
    builder: "Lodha Group",
    isActive: true,
  },
  {
    propertyName: "Elite Residency",
    propertyType: "luxury",
    city: "Delhi",
    state: "Delhi",
    address: "Connaught Place, Delhi",
    minPrice: 30000000,
    maxPrice: 60000000,
    builder: "DLF Limited",
    isActive: true,
  },
  {
    propertyName: "Sunrise Apartments",
    propertyType: "affordable",
    city: "Bangalore",
    state: "Karnataka",
    address: "Koramangala, Bangalore",
    minPrice: 8000000,
    maxPrice: 15000000,
    builder: "Prestige Group",
    isActive: true,
  },
  {
    propertyName: "Green Valley",
    propertyType: "affordable",
    city: "Pune",
    state: "Maharashtra",
    address: "Hinjewadi, Pune",
    minPrice: 7000000,
    maxPrice: 12000000,
    builder: "Kolte Patil",
    isActive: true,
  },
  {
    propertyName: "Royal Gardens",
    propertyType: "luxury",
    city: "Hyderabad",
    state: "Telangana",
    address: "Gachibowli, Hyderabad",
    minPrice: 20000000,
    maxPrice: 40000000,
    builder: "Aparna Constructions",
    isActive: true,
  },
  {
    propertyName: "City Center",
    propertyType: "affordable",
    city: "Chennai",
    state: "Tamil Nadu",
    address: "Anna Nagar, Chennai",
    minPrice: 6000000,
    maxPrice: 10000000,
    builder: "Shriram Properties",
    isActive: true,
  },
  {
    propertyName: "Ocean View",
    propertyType: "luxury",
    city: "Goa",
    state: "Goa",
    address: "Calangute Beach, Goa",
    minPrice: 35000000,
    maxPrice: 70000000,
    builder: "Gaurs Group",
    isActive: true,
  },
  {
    propertyName: "Meadow Springs",
    propertyType: "affordable",
    city: "Ahmedabad",
    state: "Gujarat",
    address: "Prahlad Nagar, Ahmedabad",
    minPrice: 5000000,
    maxPrice: 9000000,
    builder: "Adani Realty",
    isActive: true,
  },
  {
    propertyName: "Tech Park Residences",
    propertyType: "luxury",
    city: "Gurgaon",
    state: "Haryana",
    address: "DLF Phase 5, Gurgaon",
    minPrice: 28000000,
    maxPrice: 55000000,
    builder: "Emaar India",
    isActive: true,
  },
  {
    propertyName: "Harmony Homes",
    propertyType: "affordable",
    city: "Noida",
    state: "Uttar Pradesh",
    address: "Sector 62, Noida",
    minPrice: 4500000,
    maxPrice: 8500000,
    builder: "Jaypee Group",
    isActive: true,
  },
];

export const dummyLeads = [
  {
    name: "Rahul Sharma",
    phone: "9876543210",
    email: "rahul@gmail.com",
    source: "Website",
    status: "New",
  },
  {
    name: "Priya Patel",
    phone: "9876543211",
    email: "priya@gmail.com",
    source: "Walk-in",
    status: "Contacted",
  },
  {
    name: "Amit Kumar",
    phone: "9876543212",
    email: "amit@yahoo.com",
    source: "Referral",
    status: "Follow-up",
  },
  {
    name: "Sonia Singh",
    phone: "9876543213",
    email: "sonia@gmail.com",
    source: "Phone Call",
    status: "Interested",
  },
  {
    name: "Raj Verma",
    phone: "9876543214",
    email: "raj@outlook.com",
    source: "Social Media",
    status: "New",
  },
  {
    name: "Neha Gupta",
    phone: "9876543215",
    email: "neha@gmail.com",
    source: "Website",
    status: "Contacted",
  },
  {
    name: "Vikram Joshi",
    phone: "9876543216",
    email: "vikram@gmail.com",
    source: "Walk-in",
    status: "Not Interested",
  },
  {
    name: "Anjali Desai",
    phone: "9876543217",
    email: "anjali@gmail.com",
    source: "Referral",
    status: "Converted",
  },
  {
    name: "Sanjay Mehta",
    phone: "9876543218",
    email: "sanjay@gmail.com",
    source: "Campaign",
    status: "Follow-up",
  },
  {
    name: "Pooja Reddy",
    phone: "9876543219",
    email: "pooja@gmail.com",
    source: "Website",
    status: "New",
  },
  {
    name: "Karan Malhotra",
    phone: "9876543220",
    email: "karan@gmail.com",
    source: "Phone Call",
    status: "Interested",
  },
  {
    name: "Divya Nair",
    phone: "9876543221",
    email: "divya@gmail.com",
    source: "Walk-in",
    status: "Lost",
  },
  {
    name: "Ravi Iyer",
    phone: "9876543222",
    email: "ravi@gmail.com",
    source: "Social Media",
    status: "New",
  },
  {
    name: "Sneha Kapoor",
    phone: "9876543223",
    email: "sneha@gmail.com",
    source: "Referral",
    status: "Contacted",
  },
  {
    name: "Arun Choudhary",
    phone: "9876543224",
    email: "arun@gmail.com",
    source: "Website",
    status: "Follow-up",
  },
  {
    name: "Meera Shah",
    phone: "9876543225",
    email: "meera@gmail.com",
    source: "Campaign",
    status: "Interested",
  },
  {
    name: "Varun Thakur",
    phone: "9876543226",
    email: "varun@gmail.com",
    source: "Phone Call",
    status: "New",
  },
  {
    name: "Tanya Bhatia",
    phone: "9876543227",
    email: "tanya@gmail.com",
    source: "Walk-in",
    status: "Contacted",
  },
  {
    name: "Deepak Srinivas",
    phone: "9876543228",
    email: "deepak@gmail.com",
    source: "Website",
    status: "Follow-up",
  },
  {
    name: "Nisha Rao",
    phone: "9876543229",
    email: "nisha@gmail.com",
    source: "Referral",
    status: "Converted",
  },
  {
    name: "Manoj Agarwal",
    phone: "9876543230",
    email: "manoj@gmail.com",
    source: "Social Media",
    status: "New",
  },
  {
    name: "Swati Menon",
    phone: "9876543231",
    email: "swati@gmail.com",
    source: "Phone Call",
    status: "Interested",
  },
  {
    name: "Gaurav Pillai",
    phone: "9876543232",
    email: "gaurav@gmail.com",
    source: "Walk-in",
    status: "Not Interested",
  },
  {
    name: "Anita Deshmukh",
    phone: "9876543233",
    email: "anita@gmail.com",
    source: "Website",
    status: "New",
  },
  {
    name: "Rohit Nambiar",
    phone: "9876543234",
    email: "rohit@gmail.com",
    source: "Campaign",
    status: "Contacted",
  },
  {
    name: "Kavita Saxena",
    phone: "9876543235",
    email: "kavita@gmail.com",
    source: "Referral",
    status: "Follow-up",
  },
  {
    name: "Suresh Gowda",
    phone: "9876543236",
    email: "suresh@gmail.com",
    source: "Phone Call",
    status: "Interested",
  },
  {
    name: "Madhuri Dixit",
    phone: "9876543237",
    email: "madhuri@gmail.com",
    source: "Walk-in",
    status: "New",
  },
  {
    name: "Alok Tripathi",
    phone: "9876543238",
    email: "alok@gmail.com",
    source: "Website",
    status: "Contacted",
  },
  {
    name: "Shweta Bansal",
    phone: "9876543239",
    email: "shweta@gmail.com",
    source: "Social Media",
    status: "Converted",
  },
];
